=== iptc/ikos-dev/JSON-scheme/IKOS-schema-0.1.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "https://iptc.org/std/IKOS/IKOS-schema-0.1.json",
	"title": "IPTC Knowledge Organisation System - JSON -- DRAFT v0.1",
	"description": "Describes a scheme (Controlled Vocabulary, taxonomy) as a whole and each of its concepts -- copyright 2015 IPTC - International Press Telecommunications Council - www.iptc.org - This document is published under the Creative Commons Attribution 4.0 license, see  http://creativecommons.org/licenses/by/4.0/",
	"type": "object",
	"properties": {
		"uri": {
			"$ref": "#/definitions/URI"
		},
		"type": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/URI"
			}
		},
		"prefAlias": {
			"type": "string"
		},
		"prefLabel": {
			"$ref": "#/definitions/AltLanguages"
		},
		"definition": {
			"$ref": "#/definitions/AltLanguages"
		},
		"changeNote": {
			"$ref": "#/definitions/AltLanguages"
		},
		"editorialNote": {
			"$ref": "#/definitions/AltLanguages"
		},
		"authority": {
			"$ref": "#/definitions/URI"
		},
		"licenseLink": {
			"$ref": "#/definitions/URI"
		},
		"availLang": {
			"type": "array",
			"items": {
				"type": "string",
				"pattern": "^(((([A-Za-z]{2,3}(-([A-Za-z]{3}(-[A-Za-z]{3}){0,2}))?)|[A-Za-z]{4}|[A-Za-z]{5,8})(-([A-Za-z]{4}))?(-([A-Za-z]{2}|[0-9]{3}))?(-([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-([0-9A-WY-Za-wy-z](-[A-Za-z0-9]{2,8})+))*(-(x(-[A-Za-z0-9]{1,8})+))?)|(x(-[A-Za-z0-9]{1,8})+))$"
			}
		},
		"hasTopConcept": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/URI"
			}
		},
		"conceptSet": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/Concept"
			}
		}
	},
	"required": [
		"uri",
		"type"
	],
	"additionalProperties": false,
	"definitions": {
		"URI": {
			"type": "string",
			"format": "uri"
		},
		"AltLanguages": {
			"type": "object",
			"patternProperties": {
				"^(((([A-Za-z]{2,3}(-([A-Za-z]{3}(-[A-Za-z]{3}){0,2}))?)|[A-Za-z]{4}|[A-Za-z]{5,8})(-([A-Za-z]{4}))?(-([A-Za-z]{2}|[0-9]{3}))?(-([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-([0-9A-WY-Za-wy-z](-[A-Za-z0-9]{2,8})+))*(-(x(-[A-Za-z0-9]{1,8})+))?)|(x(-[A-Za-z0-9]{1,8})+))$": {
					"title": "Language tagged text",
					"description": "Property name is a BCP47 language tag, property value a text using this language",
					"type": "string"
				}
			},
			"additionalProperties": false
		},
		"Concept": {
			"type": "object",
			"properties": {
				"uri": {
					"$ref": "#/definitions/URI"
				},
				"qcode": {
					"type": "string",
					"pattern": "[^\\s:]+:[^\\s]+"
				},
				"type": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/URI"
					}
				},
				"inScheme": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/URI"
					}
				},
				"topConceptOf": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/URI"
					}
				},
				"created": {
					"type": "string",
					"format": "date-time"
				},
				"modified": {
					"type": "string",
					"format": "date-time"
				},
				"retired": {
					"type": "string",
					"format": "date-time"
				},
				"prefLabel": {
					"$ref": "#/definitions/AltLanguages"
				},
				"definition": {
					"$ref": "#/definitions/AltLanguages"
				},
				"changeNote": {
					"$ref": "#/definitions/AltLanguages"
				},
				"editorialNote": {
					"$ref": "#/definitions/AltLanguages"
				},
				"broader": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/URI"
					}
				},
				"narrower": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/URI"
					}
				},
				"exactMatch": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/URI"
					}
				},
				"closeMatch": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/URI"
					}
				},
				"broadMatch": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/URI"
					}
				}
			},
			"additionalProperties": false
		}
	}
}

=== iptc/ikos-dev/JSON-scheme/samples/IKOS-sample01.json
{
	"uri": "http://cv.iptc.org/newscodes/scene/",
	"type": [
		"http://www.w3.org/2004/02/skos/core#ConceptScheme"
	],
	"prefAlias": "scn",
	"prefLabel": {
		"en-GB": "IPTC Scene NewsCodes"
	},
	"definition": {
		"en-GB": "Indicates a type of scene covered by an item."
	},
	"editorialNote": {"en-GB":"This is a vague reflection of the real IPTC Scene NewsCodes - just for IKOS-scheme testing purposes"},
	"authority": "https://www.iptc.org",
	"licenseLink": "http://creativecommons.org/licenses/by/4.0/",
	"availLang": [
		"en-GB", "de"
	],
	"hasTopConcept": [
		"http://cv.iptc.org/newscodes/scene/010100", "http://cv.iptc.org/newscodes/scene/010200"
	],
	"conceptSet": [
		{
			"uri": "http://cv.iptc.org/newscodes/scene/010100",
			"type": [
				"http://www.w3.org/2004/02/skos/core#Concept", "http://cv.iptc.org/newscodes/cpnature/abstract"
			],
			"qcode": "scn:010100",
			"created": "2008-01-01T01:00:00+00:00",
			"modified": "2015-09-09T00:00:00+00:00",
			"inScheme": [
				"http://cv.iptc.org/newscodes/scene/"
			],
			"topConceptOf": [
				"http://cv.iptc.org/newscodes/scene/"
			],
			"prefLabel": {
				"en-GB": "headshot",
				"de": "Portrait"
			},
			"definition": {
				"en-GB": "A head only view of a person (or animal/s) or persons as in a montage.",
				"de": "Ansicht nur des Kopfes einer oder mehrerer Personen oder von einem oder mehreren Tieren."
			},
			"closeMatch": [
				"https://www.wikidata.org/entity/Q134307"
			]
		}, {
			"uri": "http://cv.iptc.org/newscodes/scene/010200",
			"type": [
				"http://www.w3.org/2004/02/skos/core#Concept", "http://cv.iptc.org/newscodes/cpnature/abstract"
			],
			"qcode": "scn:010200",
			"created": "2008-01-01T01:00:00+00:00",
			"modified": "2015-09-09T00:00:00+00:00",
			"inScheme": [
				"http://cv.iptc.org/newscodes/scene/"
			],
			"topConceptOf": [
				"http://cv.iptc.org/newscodes/scene/"
			],
			"narrower": [
				"http://cv.iptc.org/newscodes/scene/010201"
			],
			"prefLabel": {
				"en-GB": "half-length",
				"de": "Halbfigur"
			},
			"definition": {
				"en-GB": "A torso and head view of a person or persons. ",
				"de": "Ansicht des Oberkörpers einer oder mehrerer Personen."
			}
		}, {
			"uri": "http://cv.iptc.org/newscodes/scene/010201",
			"type": [
				"http://www.w3.org/2004/02/skos/core#Concept", "http://cv.iptc.org/newscodes/cpnature/abstract"
			],
			"qcode":  "scn:010201",
			"created": "2015-09-09T00:00:00+00:00",
			"modified": "2015-09-09T00:00:00+00:00",
			"retired": "2015-09-09T23:59:59+00:00",
			"inScheme": [
				"http://cv.iptc.org/newscodes/scene/"
			],
			"broader": [
				"http://cv.iptc.org/newscodes/scene/010200"
			],
			"prefLabel": {
				"en-GB": "dummy half of half-length",
				"de": "Dummy halbe Halbfigur"
			},
			"definition": {
				"en-GB": "A dummy concept for testing only",
				"de": "Ein Dummy-Begriff, nur für Tests"
			}
		}
	]
}
